# Version of your assets, change this if you want to expire all your assets.
Rails.application.config.assets.version = '1.0'
# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in app/assets folder are already added.
# Rails.application.config.assets.precompile += %w( search.js )
Rails.application.config.assets.precompile += %w( material.js )
Rails.application.config.assets.precompile += %w( index.js )
Rails.application.config.assets.precompile += %w( index.css)
Rails.application.config.assets.precompile += %w( user.js )
Rails.application.config.assets.precompile += %w( user/general.js )
Rails.application.config.assets.precompile += %w( user/history.js )
Rails.application.config.assets.precompile += %w( user/library.js )
Rails.application.config.assets.precompile += %w( user/ratings.js )
Rails.application.config.assets.precompile += %w( user/trends.js )
Rails.application.config.assets.precompile += %w( user.css )
Rails.application.config.assets.precompile += %w( user/general.css )
Rails.application.config.assets.precompile += %w( user/history.css )
Rails.application.config.assets.precompile += %w( user/library.css )
Rails.application.config.assets.precompile += %w( user/ratings.css )
Rails.application.config.assets.precompile += %w( user/trends.css )
Rails.application.config.assets.precompile += %w( admin.js )
Rails.application.config.assets.precompile += %w( admin.css )
Rails.application.config.assets.precompile += %w( jquery.js )
Rails.application.config.assets.precompile += %w( jquery-ui.min.css )
Rails.application.config.assets.precompile += %w( jquery-ui.min.js )
Rails.application.config.assets.precompile += %w( highcharts/highcharts.js )
Rails.application.config.assets.precompile += %w( highcharts/highcharts-more.js )
Rails.application.config.assets.precompile += %w( highcharts/heatmap.js )
Rails.application.config.assets.precompile += %w( highcharts/exporting.js )
Rails.application.config.assets.precompile += %w( highcharts/solid-gauge.js )
Rails.application.config.assets.precompile += %w( listjs.js )
